Repository jwflory/django-rit-grasa, pull requests merged in 2019-10, with the labels that each got.

#33 Standardize development environment on validated working changes
  Dockerfile
  docker-compose.yml
Labels: bug

#35 templates: Restore @ldidonato CSS, hook into static dir
  grasa_event_locator/static/css/custom.css
  grasa_event_locator/templates/base.html
  grasa_event_locator/templates/styles/style.css
Labels: enhancement

#36 Docker: Auto-reload changes without rebuilding container
  Dockerfile
  Procfile
  docker-compose.yml
  libs/.keep
  public/.keep
  tox.ini
Labels: enhancement

#48 gitignore: Add whoosh_index, add JetBrains IDEs
  .gitignore
Labels: enhancement

#47 docs: Add page about installing new project dependencies (closes #45)
  docs/dev/howto-add-dependencies.md
  docs/dev/howto-setup-dev-environment.md
  docs/index.rst
Labels: documentation

#52 fixed forms on search page to work with py code
  grasa_event_locator/models.py
  grasa_event_locator/static/css/custom.css
  grasa_event_locator/templates/createEvent.php
  grasa_event_locator/templates/event.php
  grasa_event_locator/templates/search/search.html
  grasa_event_locator/views.py
Labels: bug

#53 Modal/Create Event
  grasa_event_locator/templates/allUsers.php
  grasa_event_locator/templates/createEvent.php
  grasa_event_locator/templates/index.php
  grasa_event_locator/views.py
Labels: bug

#50 mysql: Set sql_mode to STRICT_TRANS_TABLE
  grasa_event_locator/settings/development.py
  grasa_event_locator/settings/production.py
Labels: bug

#56 docs: Add Troubleshooting section to dev env doc, misc. refactoring
  docs/dev/howto-add-dependencies.md
  docs/dev/howto-setup-dev-environment.md
Labels: documentation

#57 Update project dependencies to latest stable versions
  Pipfile
  Pipfile.lock
Labels: enhancement

#55 docs: Create howto docs for Docker debugging and rebuilding indexes
  docs/howto/exec-container.md
  docs/howto/rebuild-indexes.md
  docs/index.rst
Labels: documentation

#58 Add issue templates for faster filling of issues
  .github/ISSUE_TEMPLATE/01-new-story-frontend.md
  .github/ISSUE_TEMPLATE/02-new-story-backend.md
  .github/ISSUE_TEMPLATE/03-bug-report.md
  .github/ISSUE_TEMPLATE/04-other.md
Labels: documentation

#63 Hleong2 back end
  grasa_event_locator/migrations/0001_initial.py
  grasa_event_locator/models.py
  grasa_event_locator/templates/allUsers.php
  grasa_event_locator/templates/header.php
  grasa_event_locator/urls.py
  grasa_event_locator/views.py
Labels: backend, improvement

#67 ci: Add Travis job for docs and building Docker image
  .travis.yml
Labels: improvement, infra, quality assurance

#65 docs: Add page on creating first admin users
  docs/howto/add-first-admin.md
Labels: documentation, new change

#68 Hleong back end
  grasa_event_locator/models.py
  grasa_event_locator/templates/admin.php
Labels: backend, frontend, improvement

#74 docs: Add setup step for config file
  docs/dev/howto-setup-dev-environment.md
Labels: documentation, improvement

#73 Bug template: Add Stacktrace section
  .github/ISSUE_TEMPLATE/03-bug-report.md
Labels: documentation, improvement

#85 Home Page Empty Database Fix
  grasa_event_locator/views.py
Labels: backend, bug, needs review

#70 Lei front end
  grasa_event_locator/static/css/custom.css
  grasa_event_locator/templates/changePW.php
  grasa_event_locator/templates/index.php
  grasa_event_locator/templates/login.php
  grasa_event_locator/templates/register.php
Labels: frontend, improvement

#93 Dockerfile: Change image to python:3.6 -> python:3.6-stretch
  Dockerfile
Labels: bug, infra

#96 migrations: Update/delete migrations to fix startup bug
  grasa_event_locator/migrations/0001_initial.py
  grasa_event_locator/migrations/0003_auto_20191022_0148.py
Labels: backend, bug

#95 Docker Compose: Use named volume for MariaDB
  docker-compose.yml
Labels: bug, infra

#94 docs: Add page for user testing from @leiyinmon notes
  docs/howto/conduct-user-testing.md
Labels: documentation, new change

#120 speeding up container build times and locking version numbers (closes #38)
  Dockerfile
  Pipfile
  Pipfile.lock
Labels: improvement, infra

#124 docs: Remove unpublished API docs
  docs/api/example-api-usage.rst
  docs/index.rst
Labels: documentation, improvement

#121 More email implementation
  grasa_event_locator/functions.py
  grasa_event_locator/migrations/0001_initial.py
  grasa_event_locator/models.py
  grasa_event_locator/templates/allAdmins.php
  grasa_event_locator/templates/header.php
  grasa_event_locator/views.py
Labels: backend, improvement

#127 Update provider.php
  grasa_event_locator/templates/provider.php
Labels: frontend, improvement

#132 Update views.py
  grasa_event_locator/views.py
Labels: backend, improvement

#135 delete modal for provider
  grasa_event_locator/templates/header.php
  grasa_event_locator/templates/provider.php
Labels: frontend, improvement
