Repository jwflory/django-rit-grasa, pull requests merged in 2019-11, with the labels that each got.

#137 Delete 0001_initial.py
  grasa_event_locator/migrations/0001_initial.py
Labels: bug, infra

#143 docs: Add instructions on fresh starts (from @leong96 notes)
  docs/dev/start-fresh.md
Labels: documentation, new change

#144 docs: Add developer troubleshooting FAQ
  docs/dev/troubleshooting.md
Labels: documentation, new change

#142 Sprint 4 documentation clean-up and polish
  docs/about/about-project.md
  docs/about/features.md
  docs/howto/add-dependencies.md
  docs/index.rst
Labels: documentation, improvement

#138 Phone number auto fill and password validation
  grasa_event_locator/templates/createEvent.php
  grasa_event_locator/templates/editEvent.php
  grasa_event_locator/templates/register.php
Labels: frontend, new change

#149 Lauren fe 8
  grasa_event_locator/static/css/custom.css
  grasa_event_locator/templates/admin.php
  grasa_event_locator/templates/event.php
  grasa_event_locator/templates/provider.php
Labels: bug, frontend, new change

#148 'All' Pages all done + bug fixes
  grasa_event_locator/forms.py
  grasa_event_locator/functions.py
  grasa_event_locator/models.py
  grasa_event_locator/templates/allAdmins.php
  grasa_event_locator/templates/allEvents.php
  grasa_event_locator/templates/allUsers.php
  grasa_event_locator/templates/editEvent.php
  grasa_event_locator/templates/event.php
  grasa_event_locator/templates/header.php
  grasa_event_locator/templates/provider.php
  grasa_event_locator/templates/search/search.html
  grasa_event_locator/urls.py
  grasa_event_locator/views.py
Labels: backend, bug, frontend, improvement, needs review, new change

#150 Invalid Email Format Handling
  grasa_event_locator/templates/allAdmins.php
  grasa_event_locator/views.py
Labels: backend, improvement

#151 Lei front end
  grasa_event_locator/static/css/custom.css
  grasa_event_locator/templates/createEvent.php
  grasa_event_locator/templates/editEvent.php
Labels: bug, frontend

#158 URL fix
  grasa_event_locator/templates/event.php
  grasa_event_locator/views.py
Labels: backend, bug

#163 config: Add `admin_email` to example config
  config.yml.example
Labels: backend, improvement, infra

#165 Update start-fresh.md
  docs/dev/start-fresh.md
Labels: documentation, improvement

#161 settings: Test production settings for final deployment
  grasa_event_locator/settings/base.py
  grasa_event_locator/settings/development.py
  grasa_event_locator/settings/production.py
Labels: bug, infra

#168 views: Use reverse() for homepage redirects
  grasa_event_locator/urls.py
  grasa_event_locator/views.py
Labels: backend, improvement

#171 Patch Create Admins Button
  grasa_event_locator/views.py
Labels: backend, bug

#160 Change Password Functionality
  grasa_event_locator/templates/admin.php
  grasa_event_locator/templates/provider.php
  grasa_event_locator/templates/resetPWForm.php
  grasa_event_locator/urls.py
  grasa_event_locator/views.py
Labels: backend, improvement

#170 Replaced last login
  grasa_event_locator/templates/allAdmins.php
  grasa_event_locator/views.py
Labels: backend, improvement

#172 Fix various event editing bugs
  grasa_event_locator/templates/admin.php
  grasa_event_locator/views.py
Labels: backend, bug

#169 Switch PHP extensions to HTML (closes #156)
  apps/__init__.py
  apps/base/__init__.py
  apps/base/models.py
  apps/base/templates/base/home.html
  apps/base/urls.py
  apps/base/views.py
  grasa_event_locator/settings/base.py
  grasa_event_locator/settings/development.py
  grasa_event_locator/settings/production.py
  grasa_event_locator/static/css/custom.css
  grasa_event_locator/templates/aboutContact.html
  grasa_event_locator/templates/admin.html
  grasa_event_locator/templates/allAdmins.html
  grasa_event_locator/templates/allEvents.html
  grasa_event_locator/templates/allUsers.html
  grasa_event_locator/templates/changePW.html
  grasa_event_locator/templates/changePWLogout.html
  grasa_event_locator/templates/createEvent.html
  grasa_event_locator/templates/editEvent.html
  grasa_event_locator/templates/event.html
  grasa_event_locator/templates/footer.html
  grasa_event_locator/templates/header.html
  grasa_event_locator/templates/index.php
  grasa_event_locator/templates/login.html
  grasa_event_locator/templates/provider.html
  grasa_event_locator/templates/register.html
  grasa_event_locator/templates/resetPW.html
  grasa_event_locator/templates/resetPWForm.html
  grasa_event_locator/templates/search/search.html
  grasa_event_locator/urls.py
  grasa_event_locator/views.py
Labels: backend, blocked, frontend, improvement, needs review

#179 Add SMTP config options, change template, refactor functions.py
  config.yml.example
  grasa_event_locator/functions.py
  grasa_event_locator/settings/base.py
  grasa_event_locator/templates/about.html
  grasa_event_locator/templates/footer.html
  grasa_event_locator/urls.py
  grasa_event_locator/views.py
Labels: backend, frontend, improvement

#180 about page: Add high-level project description (closes #76)
  grasa_event_locator/templates/about.html
Labels: documentation, frontend, new change

#182 Import the exception only.
  grasa_event_locator/templates/allAdmins.html
  grasa_event_locator/views.py
Labels: backend, improvement

#183 fixed "+" issue with address on search
  grasa_event_locator/templates/editEvent.html
  grasa_event_locator/templates/search/search.html
Labels: bug, frontend, improvement

#186 Reset PW Expiration
  grasa_event_locator/models.py
  grasa_event_locator/templates/resetPWForm.html
  grasa_event_locator/views.py
Labels: backend, new change

#189 Remove Print Statements / change password - notificaiton message
  grasa_event_locator/templates/admin.html
  grasa_event_locator/templates/event.html
  grasa_event_locator/templates/provider.html
  grasa_event_locator/views.py
Labels: backend, frontend, improvement

#196 Deny popups
  grasa_event_locator/templates/admin.html
  grasa_event_locator/views.py
Labels: backend, frontend, new change

#199 Add CODEOWNERS GitHub config file
  .github/CODEOWNERS
Labels: documentation, new change, quality assurance

#200 functions: Refactor category creation to use a loop
  grasa_event_locator/functions.py
Labels: backend, improvement

#203 Add initial database migration file
  grasa_event_locator/migrations/0001_initial.py
Labels: backend, infra, new change

#204 CODEOWNERS: Change Eli's GitHub username
  .github/CODEOWNERS
Labels: bug, documentation

#202 settings: Add site_name to set project hostname
  config.yml.example
Labels: backend, new change

#205 config: Load organization contact info from config (closes #157)
  config.yml.example
  grasa_event_locator/forms.py
  grasa_event_locator/helpers.py
  grasa_event_locator/models.py
  grasa_event_locator/templates/about.html
  grasa_event_locator/urls.py
  grasa_event_locator/views.py
Labels: backend, improvement

#212 view/imports: Restore removed import statements
  grasa_event_locator/views.py
Labels: backend, bug

#207 Patches
  grasa_event_locator/templates/admin.html
  grasa_event_locator/templates/allAdmins.html
  grasa_event_locator/templates/allUsers.html
  grasa_event_locator/templates/provider.html
  grasa_event_locator/views.py
Labels: backend, bug, frontend, improvement

#209 docs: Update start-fresh page based on recent changes
  docs/dev/start-fresh.md
Labels: documentation, improvement

#210 activities: Expand STEM acronym fully
  grasa_event_locator/forms.py
  grasa_event_locator/templates/header.html
Labels: backend, bug, frontend

#216 Ensure activityList is identical in all definitions
  grasa_event_locator/forms.py
  grasa_event_locator/templates/header.html
Labels: backend, bug, frontend

#217 docs: Finish Event Curation System user docs
  docs/_static/user/events/admin-deny-events.png
  docs/_static/user/events/admin-invite-provider-modal.png
  docs/_static/user/events/admin-pending-events.png
  docs/_static/user/events/admin-portal-providers.png
  docs/_static/user/events/admin-review-deny-account.png
  docs/_static/user/events/admin-review-pending-account.png
  docs/_static/user/events/admin-view-providers.png
  docs/_static/user/events/provider-panel-logout.png
  docs/user/events/admin-invite-provider.md
  docs/user/events/admin-lookup-contact.md
  docs/user/events/admin-review-account.md
  docs/user/events/admin-review-event-edit.md
  docs/user/events/admin-review-event.md
  docs/user/events/provider-event-edit.md
Labels: documentation, improvement

#218 docs: Change metadata used for PDF export
  docs/conf.py
Labels: bug, documentation

#219 docs: Fix mistype caught by @leong96
  docs/_static/user/events/admin-panel-logout.png
  docs/user/events/admin-review-event.md
Labels: bug, documentation

#220 Update admin-review-account.md
  docs/user/events/admin-review-account.md
Labels: bug, documentation

#221 removed unimplemented feature
  grasa_event_locator/templates/provider.html
Labels: bug, frontend

#226 Quickstart
  docs/howto/quickstart.md
  up.py
Labels: documentation, infra, new change

#232 docs: Add license attributions (closes #195)
  docs/about/open-source-licenses.rst
Labels: backend, documentation, new change

#233 docs: Add Search System User Documentation (closes #191)
  docs/_static/user/search/event-profile-page.png
  docs/_static/user/search/search-enter-keyword.png
  docs/_static/user/search/search-filters.png
  docs/user/search/search-events.md
  docs/user/search/share-event.md
Labels: documentation, frontend, new change

#235 Admin self-delete
  grasa_event_locator/templates/allAdmins.html
Labels: bug, frontend

#236 Got generic formatting to work
  grasa_event_locator/static/css/custom.css
  grasa_event_locator/templates/event.html
Labels: bug, frontend

#237 Added alphabetical sorting by title
  grasa_event_locator/forms.py
  grasa_event_locator/search_indexes.py
  grasa_event_locator/views.py
Labels: backend, improvement

#240 docs: Rework indexes for User Documentation
  docs/index.rst
  docs/user/base-system.rst
  docs/user/events-system.rst
  docs/user/index.rst
  docs/user/search-system.rst
Labels: bug, documentation

#242 cleaning up and polishing the startup script
  up.py
Labels: improvement, infra

#239 docs: Add Deployment Architecture (part of #192)
  docs/_static/admin/deployment-architecture.png
  docs/admin/deployment-architecture.md
Labels: documentation, infra, new change

#243 Revising quickstart doc
  docs/admin/quick-start.md
  up.py
Labels: documentation, improvement, infra

#244 docs: Add explainer page for 3rd-party APIs (closes #227)
  docs/admin/third-party-apis.md
Labels: documentation, new change

#245 Clean up style in non-app files with Black (part of #123)
  docs/conf.py
  manage.py
  up.py
Labels: backend, improvement

#246 README: Update Event Locator screenshot
  README.md
Labels: documentation, improvement

#248 CODEOWNERS: Update Python and setup script rules
  .github/CODEOWNERS
Labels: improvement, quality assurance

#247 docs: Misc. polishing and minor changes
  docs/dev/setup-dev-environment.md
  docs/index.rst
Labels: documentation, improvement

#249 adding upgrade guide
  docs/admin/upgrade.md
Labels: documentation, infra, new change

#251 Reformat all Python code to Black standard (closes #123)
  grasa_event_locator/admin.py
  grasa_event_locator/apps.py
  grasa_event_locator/forms.py
  grasa_event_locator/helpers.py
  grasa_event_locator/models.py
  grasa_event_locator/rebuild_index.py
  grasa_event_locator/search_indexes.py
  grasa_event_locator/views.py
  grasa_event_locator/wsgi.py
Labels: backend, improvement, quality assurance

#252 Add precommit lint script
  code_lint.sh
  pre_commit.sh
Labels: backend, new change, quality assurance
