Repository jwflory/django-rit-grasa, pull requests merged in 2019-09, with the labels that each got.

#1 Update license as BSD 2-Clause per signed project charter
  LICENSE.txt
  README.md
Labels: bug

#4 Issues: Add template for making new issues
  .github/ISSUE_TEMPLATE.md
Labels: documentation, enhancement

#3 Add Django project template with some configuration changes
  Pipfile
  Pipfile.lock
  Procfile
  README.md
  apps/__init__.py
  apps/base/__init__.py
  apps/base/models.py
  apps/base/templates/base/home.html
  apps/base/urls.py
  apps/base/views.py
  config/nginx-mime.types
  config/nginx.conf
  config/supervisord.conf
  config/uwsgi.ini
  grasa_event_locator/__init__.py
  grasa_event_locator/settings/__init__.py
  grasa_event_locator/settings/base.py
  grasa_event_locator/settings/development.py
  grasa_event_locator/settings/local_example.py
  grasa_event_locator/settings/production.py
  grasa_event_locator/static/css/base.css
  grasa_event_locator/static/favicon.ico
  grasa_event_locator/static/img/glyphicons-halflings-white.png
  grasa_event_locator/static/img/glyphicons-halflings.png
  grasa_event_locator/static/js/app.js
  grasa_event_locator/static/js/libs/jquery-1.11.2.min.js
  grasa_event_locator/static/js/libs/less.min.js
  grasa_event_locator/static/robots.txt
  grasa_event_locator/templates/403.html
  grasa_event_locator/templates/404.html
  grasa_event_locator/templates/500.html
  grasa_event_locator/templates/base.html
  grasa_event_locator/templates/robots.txt
  grasa_event_locator/urls.py
  grasa_event_locator/wsgi.py
  libs/.keep
  manage.py
  public/.keep
  tox.ini
Labels: enhancement

#11 Add Dockerfile with docker-compose orchestration, edit grasa_event_locator settings
  Dockerfile
  Pipfile.lock
  docker-compose.yml
  grasa_event_locator/settings/base.py
  grasa_event_locator/settings/development.py
  grasa_event_locator/settings/production.py
  grasa_event_locator/urls.py
  grasa_event_locator/wsgi.py
  manage.py
Labels: enhancement

#13 README: Add README badge for current status of docs
  README.md
Labels: documentation

#15 docs: Add "Features" page
  docs/about/features.md
Labels: documentation, enhancement
